# Generated by Django 5.2.15 on 2026-07-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dicount_type',
            new_name='discount_type',
        ),
    ]
